languageCode = "en"
languageName = "English"
weight = 1

title = "bitSheriff"

[author]
  name = "bitSheriff"
  image = "img/logo_name.png"
  headline = "Welcome to the Saloon"
  bio = "Bughunter in the Wild Wild Web"
   links = [
     { github = "https://github.com/bitSheriff/" },
     { twitter = "https://twitter.com/bitSheriff" },
     { dev = "https://dev.to/bitSheriff" },
     { link = "https://linktr.ee/bitsheriff" }
   ]
